/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.controller.api;

import com.example.hnino.biblioapps.rest.model.beans.InformationResult;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

public interface RestController {

  /**
   * Generated from URL GET https://itunes.apple.com/us/rss/topfreeapplications/limit%3D20/json
   * GET us/rss/topfreeapplications/limit%3D20/json
   * @param listener
   * @return InformationResult
   */
  Call<InformationResult> getInformation(StateChangedListener listener);
}
