/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.controller.api;

import com.example.hnino.biblioapps.rest.model.beans.InformationResult;
import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Arrays;

public class RestControllerFactory extends ControllerFactory<RestController> {
  public RestControllerFactory(MagnetMobileClient magnetClient) {
    super(RestController.class, RestControllerSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller RestController
  public static class RestControllerSchemaFactory extends AbstractControllerSchemaFactory {
    private static RestControllerSchemaFactory __instance;

    public static synchronized RestControllerSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new RestControllerSchemaFactory();
      }

      return __instance;
    }

    private RestControllerSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getInformation
      JMethod method1 = addMethod("getInformation",
        "us/rss/topfreeapplications/limit%3D20/json",
        "GET",
        InformationResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://itunes.apple.com");
    }

  }

}
