/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "height" : "53"
}

 */

public class Attributes {

  
  private String height;

  public String getHeight() {
    return height;
  }

  /**
  * Builder for Attributes
  **/
  public static class AttributesBuilder {
    private Attributes toBuild = new Attributes();

    public AttributesBuilder() {
    }

    public Attributes build() {
      return toBuild;
    }

    public AttributesBuilder height(String value) {
      toBuild.height = value;
      return this;
    }
  }
}
