/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "name" : {
    "label" : "iTunesStore"
  },
  "uri" : {
    "label" : "http://www.apple.com/itunes/"
  }
}

 */

public class Author {

  
  private Name name;

  
  private Uri uri;

  public Name getName() {
    return name;
  }
  public Uri getUri() {
    return uri;
  }

  /**
  * Builder for Author
  **/
  public static class AuthorBuilder {
    private Author toBuild = new Author();

    public AuthorBuilder() {
    }

    public Author build() {
      return toBuild;
    }

    public AuthorBuilder name(Name value) {
      toBuild.name = value;
      return this;
    }
    public AuthorBuilder uri(Uri value) {
      toBuild.uri = value;
      return this;
    }
  }
}
