/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "attributes" : {
    "im:id" : "6002",
    "term" : "Utilities",
    "scheme" : "https://itunes.apple.com/us/genre/ios-utilities/id6002?mt=8&uo=2",
    "label" : "Utilities"
  }
}

 */

public class Category {

  
  private CategoryAttributes attributes;

  public CategoryAttributes getAttributes() {
    return attributes;
  }

  /**
  * Builder for Category
  **/
  public static class CategoryBuilder {
    private Category toBuild = new Category();

    public CategoryBuilder() {
    }

    public Category build() {
      return toBuild;
    }

    public CategoryBuilder attributes(CategoryAttributes value) {
      toBuild.attributes = value;
      return this;
    }
  }
}
