/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "http://itunes.apple.com/favicon.ico"
}

 */

public class Icon {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for Icon
  **/
  public static class IconBuilder {
    private Icon toBuild = new Icon();

    public IconBuilder() {
    }

    public Icon build() {
      return toBuild;
    }

    public IconBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
