/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "https://itunes.apple.com/us/app/bitmoji-keyboard-your-avatar/id868077558?mt=8&uo=2",
  "attributes" : {
    "im:id" : "868077558",
    "im:bundleId" : "com.bitstrips.imoji"
  }
}

 */

public class Id {

  
  private IdAttributes attributes;

  
  private String label;

  public IdAttributes getAttributes() {
    return attributes;
  }
  public String getLabel() {
    return label;
  }

  /**
  * Builder for Id
  **/
  public static class IdBuilder {
    private Id toBuild = new Id();

    public IdBuilder() {
    }

    public Id build() {
      return toBuild;
    }

    public IdBuilder attributes(IdAttributes value) {
      toBuild.attributes = value;
      return this;
    }
    public IdBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
