/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "im:id" : "868077558",
  "im:bundleId" : "com.bitstrips.imoji"
}

 */

public class IdAttributes {

  
@com.google.gson.annotations.SerializedName("im:bundleId")
  private String imBundleId;

  
@com.google.gson.annotations.SerializedName("im:id")
  private String imId;

  public String getImBundleId() {
    return imBundleId;
  }
  public String getImId() {
    return imId;
  }

  /**
  * Builder for IdAttributes
  **/
  public static class IdAttributesBuilder {
    private IdAttributes toBuild = new IdAttributes();

    public IdAttributesBuilder() {
    }

    public IdAttributes build() {
      return toBuild;
    }

    public IdAttributesBuilder imBundleId(String value) {
      toBuild.imBundleId = value;
      return this;
    }
    public IdAttributesBuilder imId(String value) {
      toBuild.imId = value;
      return this;
    }
  }
}
