/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "Bitstrips",
  "attributes" : {
    "href" : "https://itunes.apple.com/us/developer/bitstrips/id694701217?mt=8&uo=2"
  }
}

 */

public class ImArtist {

  
  private ImArtistAttributes attributes;

  
  private String label;

  public ImArtistAttributes getAttributes() {
    return attributes;
  }
  public String getLabel() {
    return label;
  }

  /**
  * Builder for ImArtist
  **/
  public static class ImArtistBuilder {
    private ImArtist toBuild = new ImArtist();

    public ImArtistBuilder() {
    }

    public ImArtist build() {
      return toBuild;
    }

    public ImArtistBuilder attributes(ImArtistAttributes value) {
      toBuild.attributes = value;
      return this;
    }
    public ImArtistBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
