/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "attributes" : {
    "term" : "Application",
    "label" : "Application"
  }
}

 */

public class ImContentType {

  
  private ImContentTypeAttributes attributes;

  public ImContentTypeAttributes getAttributes() {
    return attributes;
  }

  /**
  * Builder for ImContentType
  **/
  public static class ImContentTypeBuilder {
    private ImContentType toBuild = new ImContentType();

    public ImContentTypeBuilder() {
    }

    public ImContentType build() {
      return toBuild;
    }

    public ImContentTypeBuilder attributes(ImContentTypeAttributes value) {
      toBuild.attributes = value;
      return this;
    }
  }
}
