/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "http://is1.mzstatic.com/image/thumb/Purple60/v4/f9/ca/a3/f9caa3f6-81ed-285d-b1e1-1492f8ead754/mzl.rhmornbv.png/53x53bb-85.png",
  "attributes" : {
    "height" : "53"
  }
}

 */

public class ImImage {

  
  private Attributes attributes;

  
  private String label;

  public Attributes getAttributes() {
    return attributes;
  }
  public String getLabel() {
    return label;
  }

  /**
  * Builder for ImImage
  **/
  public static class ImImageBuilder {
    private ImImage toBuild = new ImImage();

    public ImImageBuilder() {
    }

    public ImImage build() {
      return toBuild;
    }

    public ImImageBuilder attributes(Attributes value) {
      toBuild.attributes = value;
      return this;
    }
    public ImImageBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
