/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "Get",
  "attributes" : {
    "amount" : "0.00000",
    "currency" : "USD"
  }
}

 */

public class ImPrice {

  
  private ImPriceAttributes attributes;

  
  private String label;

  public ImPriceAttributes getAttributes() {
    return attributes;
  }
  public String getLabel() {
    return label;
  }

  /**
  * Builder for ImPrice
  **/
  public static class ImPriceBuilder {
    private ImPrice toBuild = new ImPrice();

    public ImPriceBuilder() {
    }

    public ImPrice build() {
      return toBuild;
    }

    public ImPriceBuilder attributes(ImPriceAttributes value) {
      toBuild.attributes = value;
      return this;
    }
    public ImPriceBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
