/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "amount" : "0.00000",
  "currency" : "USD"
}

 */

public class ImPriceAttributes {

  
  private String amount;

  
  private String currency;

  public String getAmount() {
    return amount;
  }
  public String getCurrency() {
    return currency;
  }

  /**
  * Builder for ImPriceAttributes
  **/
  public static class ImPriceAttributesBuilder {
    private ImPriceAttributes toBuild = new ImPriceAttributes();

    public ImPriceAttributesBuilder() {
    }

    public ImPriceAttributes build() {
      return toBuild;
    }

    public ImPriceAttributesBuilder amount(String value) {
      toBuild.amount = value;
      return this;
    }
    public ImPriceAttributesBuilder currency(String value) {
      toBuild.currency = value;
      return this;
    }
  }
}
