/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "October28,2014"
}

 */

public class ImReleaseDateAttributes {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for ImReleaseDateAttributes
  **/
  public static class ImReleaseDateAttributesBuilder {
    private ImReleaseDateAttributes toBuild = new ImReleaseDateAttributes();

    public ImReleaseDateAttributesBuilder() {
    }

    public ImReleaseDateAttributes build() {
      return toBuild;
    }

    public ImReleaseDateAttributesBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
