/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "feed" : {
    "author" : {
      "name" : {
        "label" : "iTunesStore"
      },
      "uri" : {
        "label" : "http://www.apple.com/itunes/"
      }
    },
    "entry" : [ {
      "im:name" : {
        "label" : "BitmojiKeyboard-YourAvatarEmoji"
      },
      "im:image" : [ {
        "label" : "http://is1.mzstatic.com/image/thumb/Purple60/v4/f9/ca/a3/f9caa3f6-81ed-285d-b1e1-1492f8ead754/mzl.rhmornbv.png/53x53bb-85.png",
        "attributes" : {
          "height" : "53"
        }
      }, {
          ...

 */

public class InformationResult {

  
  private Feed feed;

  public Feed getFeed() {
    return feed;
  }

  /**
  * Builder for InformationResult
  **/
  public static class InformationResultBuilder {
    private InformationResult toBuild = new InformationResult();

    public InformationResultBuilder() {
    }

    public InformationResult build() {
      return toBuild;
    }

    public InformationResultBuilder feed(Feed value) {
      toBuild.feed = value;
      return this;
    }
  }
}
