/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "attributes" : {
    "rel" : "alternate",
    "type" : "text/html",
    "href" : "https://itunes.apple.com/us/app/bitmoji-keyboard-your-avatar/id868077558?mt=8&uo=2"
  }
}

 */

public class Link {

  
  private LinkAttributes attributes;

  public LinkAttributes getAttributes() {
    return attributes;
  }

  /**
  * Builder for Link
  **/
  public static class LinkBuilder {
    private Link toBuild = new Link();

    public LinkBuilder() {
    }

    public Link build() {
      return toBuild;
    }

    public LinkBuilder attributes(LinkAttributes value) {
      toBuild.attributes = value;
      return this;
    }
  }
}
