/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "rel" : "alternate",
  "type" : "text/html",
  "href" : "https://itunes.apple.com/us/app/bitmoji-keyboard-your-avatar/id868077558?mt=8&uo=2"
}

 */

public class LinkAttributes {

  
  private String href;

  
  private String rel;

  
  private String type;

  public String getHref() {
    return href;
  }
  public String getRel() {
    return rel;
  }
  public String getType() {
    return type;
  }

  /**
  * Builder for LinkAttributes
  **/
  public static class LinkAttributesBuilder {
    private LinkAttributes toBuild = new LinkAttributes();

    public LinkAttributesBuilder() {
    }

    public LinkAttributes build() {
      return toBuild;
    }

    public LinkAttributesBuilder href(String value) {
      toBuild.href = value;
      return this;
    }
    public LinkAttributesBuilder rel(String value) {
      toBuild.rel = value;
      return this;
    }
    public LinkAttributesBuilder type(String value) {
      toBuild.type = value;
      return this;
    }
  }
}
