/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "iTunesStore"
}

 */

public class Name {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for Name
  **/
  public static class NameBuilder {
    private Name toBuild = new Name();

    public NameBuilder() {
    }

    public Name build() {
      return toBuild;
    }

    public NameBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
