/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "Bitmojiisyourownpersonalemoji.\n\n•Createanexpressivecartoonavatar\n•Choosefromahugelibraryofstickers–allfeaturingYOU\n•UseBitmojiinSnapchat,iMessageandwhereverelseyouchat\n\nUsingBitmojiinSnapchatunlocksfriendmoji–2-personbitmojisfeaturingyouandyourfriends!"
}

 */

public class Summary {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for Summary
  **/
  public static class SummaryBuilder {
    private Summary toBuild = new Summary();

    public SummaryBuilder() {
    }

    public Summary build() {
      return toBuild;
    }

    public SummaryBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
