/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "BitmojiKeyboard-YourAvatarEmoji-Bitstrips"
}

 */

public class Title {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for Title
  **/
  public static class TitleBuilder {
    private Title toBuild = new Title();

    public TitleBuilder() {
    }

    public Title build() {
      return toBuild;
    }

    public TitleBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
