/**
 * File generated by Magnet rest2mobile 1.1 - 21/08/2016 03:42:06 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.hnino.biblioapps.rest.model.beans;


/**
 * Generated from json example
{
  "label" : "http://www.apple.com/itunes/"
}

 */

public class Uri {

  
  private String label;

  public String getLabel() {
    return label;
  }

  /**
  * Builder for Uri
  **/
  public static class UriBuilder {
    private Uri toBuild = new Uri();

    public UriBuilder() {
    }

    public Uri build() {
      return toBuild;
    }

    public UriBuilder label(String value) {
      toBuild.label = value;
      return this;
    }
  }
}
