package com.example.hnino.biblioapps.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hnino.biblioapps.greendao.App;
import com.example.hnino.biblioapps.greendao.Category;
import com.example.hnino.biblioapps.greendao.Image;

import com.example.hnino.biblioapps.greendao.AppDao;
import com.example.hnino.biblioapps.greendao.CategoryDao;
import com.example.hnino.biblioapps.greendao.ImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig imageDaoConfig;

    private final AppDao appDao;
    private final CategoryDao categoryDao;
    private final ImageDao imageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        appDao = new AppDao(appDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);

        registerDao(App.class, appDao);
        registerDao(Category.class, categoryDao);
        registerDao(Image.class, imageDao);
    }
    
    public void clear() {
        appDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
    }

    public AppDao getAppDao() {
        return appDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

}
