package com.example.hnino.biblioapps.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IMAGE".
 */
public class Image {

    private Long id;
    /** Not-null value. */
    private String url;
    private int height;
    private long appId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String url, int height, long appId) {
        this.id = id;
        this.url = url;
        this.height = height;
        this.appId = appId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
